src/App.js, src/custom.css
=> Add font and improve search button

package-lock.json, package.json, src/App.js, src/config/engine.json
- Use the new elastic search engine `bitcoin-search-engine`
- Sanitize the title and body
- Improve display of body
=> Improve body rendering

src/App.js, src/custom.css
I'd prefer this approach to #3
=> drop sidebar at 1200px, remove triangle from url

src/App.js
This PR removes suggested queries from the search box
=> remove suggested queries from SearchBox

src/custom.css
=> Fix author label colors

src/components/customResultView/CustomResultView.jsx, src/custom.css
=> added date to search results

src/components/customResultView/CustomResultView.jsx, src/components/customResultView/Thumbnail.jsx, src/config/mapping.json, src/custom.css, src/utils/views.js
=> added youtube thumbnails

src/App.jsx
=> feat: scroll on page change

src/components/customSearchboxView/SearchInput.jsx, src/custom.scss
=> feat: added annotations with transition

src/config/engine.json
=> feat: removed-tags

src/App.jsx, src/components/loadingBar/LoadingBar.jsx, src/components/loadingBar/loadingBar.scss, src/custom.scss, src/styles/reset.css
=> Loading state

package-lock.json, package.json, src/App.jsx, src/chakra/chakra-theme.js, src/chakra/components/Button.js, src/components/customPagingInfo/CustomPagingInfo.jsx, src/components/customPagingInfo/customPagingInfoView.jsx, src/components/customResults/CustomResults.jsx, src/components/filterTag/FilterTags.jsx, src/components/filterTag/filterTags.scss, src/components/footer/Footer.jsx, src/components/homeFacetSelection/KeywordsSelection.jsx, src/components/homeFacetSelection/index.jsx, src/config/config-helper.js, src/config/engine.json, src/custom.scss, src/hooks/useIsInitialStateWithoutFilter.js, src/hooks/useSearchContext.js, src/index.jsx, src/layout/Header.jsx, src/layout/SideBar.jsx
This PR addresses the request raised on this other PR: https://github.com/bitcoinsearch/bitcoinsearch-app/pull/60#issuecomment-1448896295
It should be merged after https://github.com/bitcoinsearch/bitcoinsearch-app/pull/60 is merged.
=> Facet selection homepage improvements

src/App.jsx, src/components/footer/Footer.jsx, src/components/footer/HomeFooter.jsx, src/components/footer/footer.scss, src/custom.scss
Closes https://github.com/bitcoinsearch/bitcoinsearch-app/issues/63
=> feat: add link to chaincode

.gitignore, src/components/footer/footer.scss
This PR fixes the issue with the footer on the home page not fixed to the bottom on smaller devices (mobile)
=> fix: position footer as fixed

src/pages/index.tsx
=> remove banner

src/components/customMultiCheckboxFacet/CustomMultiCheckboxFacet.tsx, src/components/customSearchboxView/SearchBoxView.tsx, src/layout/Header.tsx, src/layout/Layout.tsx, src/layout/SideBar.tsx
https://github.com/bitcoinsearch/bitcoinsearch-app/assets/62019510/6143913e-afb5-439a-ac31-9f07a6979044
https://github.com/bitcoinsearch/bitcoinsearch-app/assets/62019510/7f988ee5-dc15-4688-bf65-1d4da7a5244f
On IOS if an input element has a font size less than 16px it causes it to zoom (punch in) when the input box is clicked, which is s terrible UX. This PR enables the input elements are 16px on small screens
=> Styling fixes

README.md, src/context/SearchQueryContext.tsx, src/service/api/search/useSearch.ts, src/utils/server/apiFunctions.ts
Refined project documentation and added comments during an in-depth review to map out the project's architecture and component interactions. Open to feedback and further contributions.
=> Enhance documentation

src/components/formModal/FormModal.tsx, src/pages/index.tsx
=> feat: optional email requirement

src/components/customResults/Result.tsx
issue: Shown in image above
fix: remove premature replaceAll new lines. Handled by parser
=> fix: rm replaceAll new lines to empty string, handled by parser

package.json, src/components/Banner.tsx, src/components/navBar/NavBar.tsx, src/pages/_app.tsx, src/pages/index.tsx
=> Addition of boss banner

src/components/footer/Footer.tsx
This PR changes our feedback link
=> Changed feedback link to google
